version: '3'
services:
  moderation-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDISHOST=${REDISHOST}
      - REDISPASSWORD=${REDISPASSWORD}
      - REDISPORT=${REDISPORT}
      - REDISUSER=${REDISUSER}
    volumes:
      - ./downloads:/app/downloads
    ports:
      - "8080:8080"